from __future__ import annotations

import re

from app.config import get_settings
from app.schemas.render import RenderRequest


async def generate_script(payload: RenderRequest) -> str:
    """Generate or normalize the script for prompt/script launch workflows."""

    if payload.source.text:
        return payload.source.text.strip()
    if payload.source.prompt:
        prompt = payload.source.prompt.strip()
        return (
            f"Hook: {prompt}\n"
            f"Value: Explain the value clearly with one vivid proof point.\n"
            f"CTA: End with a confident call to action."
        )
    return "Scaffold script generated by the pipeline stub."


async def split_scenes(script: str, payload: RenderRequest) -> list[dict[str, object]]:
    """Split the script into launch scenes sized for ai-video clip generation."""

    chunks = [chunk.strip() for chunk in script.replace("\r", "").split("\n") if chunk.strip()]
    if not chunks:
        chunks = [script.strip() or "Launch video scene."]

    scene_duration = max(
        4,
        int((payload.source.duration_seconds or payload.options.prompt_target_duration or 24) / len(chunks)),
    )
    style_prompt = payload.source.style_prompt or "Cinematic short-form video scene."
    return [
        {
            "text": chunk,
            "visualPrompt": f"{style_prompt} {chunk}".strip(),
            "durationSeconds": scene_duration,
        }
        for chunk in chunks
    ]


def _five_beat_chunks(script: str) -> list[str]:
    chunks = [chunk.strip() for chunk in script.replace("\r", "").split("\n") if chunk.strip()]
    if len(chunks) >= 5:
        return chunks[:5]

    sentences = [
        sentence.strip()
        for sentence in re.split(r"(?<=[.!?])\s+", script.replace("\n", " ").strip())
        if sentence.strip()
    ]
    if not sentences:
        sentences = [script.strip() or "Introduce the story visually."]

    while len(sentences) < 5:
        if len(sentences) == 1:
            sentences.append("Introduce the main character with a memorable visual cue.")
        elif len(sentences) == 2:
            sentences.append("Show the first visual escalation or challenge.")
        elif len(sentences) == 3:
            sentences.append("Reveal the transformation or key insight.")
        else:
            sentences.append("Land the story with a strong final image.")
    return sentences[:5]


async def split_image_story_scenes(script: str, payload: RenderRequest) -> list[dict[str, object]]:
    """Build a fixed five-image story plan with a recurring character bible."""

    story_beats = _five_beat_chunks(script)
    total_duration = int(payload.source.duration_seconds or payload.options.prompt_target_duration or 25)
    scene_duration = max(4, int(total_duration / max(len(story_beats), 1)))
    style_prompt = payload.source.style_prompt or "Premium vertical story frames with cinematic composition."
    prompt_seed = payload.source.prompt or payload.source.text or "A memorable product story"
    seed_fragment = prompt_seed.strip().replace("\n", " ")[:120]
    character_bible = (
        "Same protagonist in every frame, consistent wardrobe, hairstyle, facial features, and premium brand world. "
        f"Core story: {seed_fragment}."
    )

    labels = ["Hook", "Setup", "Escalation", "Payoff", "CTA"]
    scenes: list[dict[str, object]] = []
    for index, beat in enumerate(story_beats):
        label = labels[index]
        visual_prompt = (
            f"{style_prompt[:180]} {character_bible} {label} frame. {beat[:180]} "
            "Photorealistic, highly detailed, social-first, no text overlay."
        ).strip()
        scenes.append(
            {
                "text": beat,
                "visualPrompt": visual_prompt,
                "durationSeconds": scene_duration,
                "storyLabel": label,
                "storyBible": character_bible,
            }
        )
    return scenes


def _three_beat_chunks(script: str) -> list[str]:
    chunks = [chunk.strip() for chunk in script.replace("\r", "").split("\n") if chunk.strip()]
    if len(chunks) >= 3:
        return chunks[:3]

    sentences = [
        sentence.strip()
        for sentence in re.split(r"(?<=[.!?])\s+", script.replace("\n", " ").strip())
        if sentence.strip()
    ]
    if not sentences:
        sentences = [script.strip() or "Introduce the offer clearly."]

    if len(sentences) >= 3:
        midpoint = max(1, len(sentences) // 2)
        return [
            " ".join(sentences[:1]).strip(),
            " ".join(sentences[1:midpoint + 1]).strip() or sentences[min(1, len(sentences) - 1)],
            " ".join(sentences[midpoint + 1 :]).strip() or sentences[-1],
        ]

    while len(sentences) < 3:
        if len(sentences) == 1:
            sentences.append("Show supporting visual proof that strengthens the message.")
        else:
            sentences.append("Close with a clear call to action.")
    return sentences[:3]


async def split_avatar_scenes(script: str, payload: RenderRequest) -> list[dict[str, object]]:
    """Build a fixed three-scene avatar plan using the default avatar reference image."""

    settings = get_settings()
    avatar_url = payload.avatar.url if payload.avatar and payload.avatar.url else settings.default_avatar_image_url
    avatar_mime_type = (
        payload.avatar.mime_type if payload.avatar and payload.avatar.mime_type else settings.default_avatar_image_mime_type
    )
    character_prompt = settings.default_avatar_character_prompt
    if payload.source.style_prompt:
        character_prompt = f"{character_prompt} {payload.source.style_prompt}".strip()

    beats = _three_beat_chunks(script)
    scene_specs = [
        (
            "talking-head",
            "Medium close-up vertical talking-head shot. The presenter looks straight into camera and delivers the line naturally.",
        ),
        (
            "supporting",
            "Supporting vertical scene with the same presenter and matching wardrobe, lighting, and brand world. Show contextual action and proof.",
        ),
        (
            "cta",
            "Final payoff scene with the same presenter and a confident closing beat. Keep the action clean and conversion-focused.",
        ),
    ]

    scenes: list[dict[str, object]] = []
    for index, beat in enumerate(beats):
        shot_type, shot_prompt = scene_specs[index]
        scenes.append(
            {
                "text": beat,
                "spokenText": beat,
                "shotType": shot_type,
                "visualPrompt": f"{character_prompt} {shot_prompt} {beat}".strip(),
                "durationSeconds": 6,
                "generateAudio": False,
                "referenceImageUrl": avatar_url,
                "referenceImageMimeType": avatar_mime_type,
                "referenceType": "ASSET",
                "characterPrompt": character_prompt,
            }
        )
    return scenes
